-- JENIFFER BIRTHDAY WISH WALL — SUPABASE SETUP
-- Paste this entire file into Supabase Dashboard > SQL Editor > New query.
-- Then click RUN.

create table if not exists public.birthday_wishes (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 40),
  wish text not null check (char_length(wish) between 1 and 500),
  avatar_url text not null,
  created_at timestamptz not null default now()
);

alter table public.birthday_wishes enable row level security;

drop policy if exists "Anyone can read birthday wishes" on public.birthday_wishes;
create policy "Anyone can read birthday wishes"
on public.birthday_wishes
for select
to anon
using (true);

drop policy if exists "Anyone can submit a birthday wish" on public.birthday_wishes;
create policy "Anyone can submit a birthday wish"
on public.birthday_wishes
for insert
to anon
with check (
  char_length(name) between 1 and 40
  and char_length(wish) between 1 and 500
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'birthday-avatars',
  'birthday-avatars',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = true,
  file_size_limit = 5242880,
  allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp'];

drop policy if exists "Anyone can upload a birthday avatar" on storage.objects;
create policy "Anyone can upload a birthday avatar"
on storage.objects
for insert
to anon
with check (bucket_id = 'birthday-avatars');

drop policy if exists "Anyone can view birthday avatars" on storage.objects;
create policy "Anyone can view birthday avatars"
on storage.objects
for select
to anon
using (bucket_id = 'birthday-avatars');
